name: preview_on_pr_update

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  preview:
    # only run when updating an 'Open' PR
    if: github.event.pull_request.state == 'open'
    uses: jalantechnologies/github-ci/.github/workflows/ci.yml@v1.4
    concurrency:
      group: ci-preview-${{ github.event.pull_request.head.ref }}
      cancel-in-progress: true
    with:
      analyze_base: main
      app_name: frm-boilerplate
      app_env: preview
      app_hostname: '{1}.preview.platform.jalantechnologies.com'
      branch: ${{ github.event.pull_request.head.ref }}
      build_args: |
        APP_ENV=preview
      checks: "['npm:coverage', 'npm:lint:ts', 'npm:lint:py', 'compose:test']"
      docker_registry: ${{ vars.DOCKER_REGISTRY }}
      docker_username: ${{ vars.DOCKER_USERNAME }}
      pull_request_number: ${{ github.event.number }}
      sonar_host_url: ${{ vars.SONAR_HOST_URL }}
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      doppler_token: ${{ secrets.DOPPLER_PREVIEW_TOKEN }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
      do_cluster_id: ${{ secrets.DO_CLUSTER_ID }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
